import os


def _get_int_env(name: str, default: int) -> int:
    raw = os.getenv(name, str(default)).strip()
    try:
        return int(raw)
    except ValueError:
        return default


def _get_bool_env(name: str, default: bool) -> bool:
    raw = os.getenv(name, "1" if default else "0").strip().lower()
    return raw in ("1", "true", "yes", "on")


def _get_csv_env(name: str) -> list:
    values = []
    raw = os.getenv(name, "")
    for item in str(raw).split(","):
        value = str(item or "").strip()
        if value:
            values.append(value)
    return values


NODE_TASK_RUNNING_TIMEOUT_SECONDS = int(_get_int_env("NODE_TASK_RUNNING_TIMEOUT", 120))
if NODE_TASK_RUNNING_TIMEOUT_SECONDS < 30:
    NODE_TASK_RUNNING_TIMEOUT_SECONDS = 30

NODE_TASK_RETENTION_SECONDS = int(_get_int_env("NODE_TASK_RETENTION_SECONDS", 7 * 86400))
if NODE_TASK_RETENTION_SECONDS < 3600:
    NODE_TASK_RETENTION_SECONDS = 3600

NODE_TASK_MAX_PENDING_PER_NODE = int(_get_int_env("NODE_TASK_MAX_PENDING_PER_NODE", 50))
if NODE_TASK_MAX_PENDING_PER_NODE < 1:
    NODE_TASK_MAX_PENDING_PER_NODE = 1
if NODE_TASK_MAX_PENDING_PER_NODE > 1000:
    NODE_TASK_MAX_PENDING_PER_NODE = 1000

SUB_LINK_SIGN_KEY = os.getenv("SUB_LINK_SIGN_KEY", "").strip()
SUB_LINK_REQUIRE_SIGNATURE = os.getenv("SUB_LINK_REQUIRE_SIGNATURE", "0").strip() in (
    "1",
    "true",
    "TRUE",
    "yes",
    "YES",
)
SUB_LINK_DEFAULT_TTL_SECONDS = int(_get_int_env("SUB_LINK_DEFAULT_TTL_SECONDS", 7 * 86400))
if SUB_LINK_DEFAULT_TTL_SECONDS < 60:
    SUB_LINK_DEFAULT_TTL_SECONDS = 60
if SUB_LINK_DEFAULT_TTL_SECONDS > 30 * 86400:
    SUB_LINK_DEFAULT_TTL_SECONDS = 30 * 86400

BACKUP_RETENTION_COUNT = int(_get_int_env("BACKUP_RETENTION_COUNT", 30))
if BACKUP_RETENTION_COUNT < 1:
    BACKUP_RETENTION_COUNT = 1

MIGRATE_RETENTION_COUNT = int(_get_int_env("MIGRATE_RETENTION_COUNT", 20))
if MIGRATE_RETENTION_COUNT < 1:
    MIGRATE_RETENTION_COUNT = 1

# 优先使用 controller 专用阈值；未设置时兼容 bot 既有变量，避免离线判定不一致。
NODE_MONITOR_OFFLINE_THRESHOLD_SECONDS = int(
    _get_int_env(
        "NODE_MONITOR_OFFLINE_THRESHOLD_SECONDS",
        _get_int_env("BOT_NODE_OFFLINE_THRESHOLD", 120),
    )
)
if NODE_MONITOR_OFFLINE_THRESHOLD_SECONDS < 30:
    NODE_MONITOR_OFFLINE_THRESHOLD_SECONDS = 30

# 默认过滤本机/测试来源（127.0.0.1/testclient）以便更准确观察真实公网扫描趋势。
SECURITY_EVENTS_EXCLUDE_LOCAL = _get_bool_env("SECURITY_EVENTS_EXCLUDE_LOCAL", True)

# 管理端 8080 放行白名单（可为空，来源于 .env）
CONTROLLER_PORT_WHITELIST_ITEMS = _get_csv_env("CONTROLLER_PORT_WHITELIST")

# 安全封禁保护白名单（可为空，逗号分隔 IP/CIDR；manual/auto block 会跳过这些来源）
SECURITY_BLOCK_PROTECTED_IPS_ITEMS = _get_csv_env("SECURITY_BLOCK_PROTECTED_IPS")

CONTROLLER_PORT = int(_get_int_env("CONTROLLER_PORT", 8080))
if CONTROLLER_PORT < 1 or CONTROLLER_PORT > 65535:
    CONTROLLER_PORT = 8080

CONTROLLER_PUBLIC_URL = os.getenv("CONTROLLER_PUBLIC_URL", "").strip().rstrip("/")

AGENT_DEFAULT_POLL_INTERVAL = int(_get_int_env("AGENT_DEFAULT_POLL_INTERVAL", 15))
if AGENT_DEFAULT_POLL_INTERVAL < 5:
    AGENT_DEFAULT_POLL_INTERVAL = 5
if AGENT_DEFAULT_POLL_INTERVAL > 3600:
    AGENT_DEFAULT_POLL_INTERVAL = 3600

SECURITY_BLOCK_CLEANUP_INTERVAL_SECONDS = int(_get_int_env("SECURITY_BLOCK_CLEANUP_INTERVAL_SECONDS", 60))
if SECURITY_BLOCK_CLEANUP_INTERVAL_SECONDS < 5:
    SECURITY_BLOCK_CLEANUP_INTERVAL_SECONDS = 5

SECURITY_AUTO_BLOCK_ENABLED = _get_bool_env("SECURITY_AUTO_BLOCK_ENABLED", False)

SECURITY_AUTO_BLOCK_INTERVAL_SECONDS = int(_get_int_env("SECURITY_AUTO_BLOCK_INTERVAL_SECONDS", 60))
if SECURITY_AUTO_BLOCK_INTERVAL_SECONDS < 10:
    SECURITY_AUTO_BLOCK_INTERVAL_SECONDS = 10

SECURITY_AUTO_BLOCK_WINDOW_SECONDS = int(_get_int_env("SECURITY_AUTO_BLOCK_WINDOW_SECONDS", 3600))
if SECURITY_AUTO_BLOCK_WINDOW_SECONDS < 60:
    SECURITY_AUTO_BLOCK_WINDOW_SECONDS = 60
if SECURITY_AUTO_BLOCK_WINDOW_SECONDS > 7 * 86400:
    SECURITY_AUTO_BLOCK_WINDOW_SECONDS = 7 * 86400

SECURITY_AUTO_BLOCK_THRESHOLD = int(_get_int_env("SECURITY_AUTO_BLOCK_THRESHOLD", 30))
if SECURITY_AUTO_BLOCK_THRESHOLD < 1:
    SECURITY_AUTO_BLOCK_THRESHOLD = 1

SECURITY_AUTO_BLOCK_DURATION_SECONDS = int(_get_int_env("SECURITY_AUTO_BLOCK_DURATION_SECONDS", 3600))
if SECURITY_AUTO_BLOCK_DURATION_SECONDS < 0:
    SECURITY_AUTO_BLOCK_DURATION_SECONDS = 0
if SECURITY_AUTO_BLOCK_DURATION_SECONDS > 30 * 86400:
    SECURITY_AUTO_BLOCK_DURATION_SECONDS = 30 * 86400

SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL = int(_get_int_env("SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL", 5))
if SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL < 1:
    SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL = 1
if SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL > 100:
    SECURITY_AUTO_BLOCK_MAX_PER_INTERVAL = 100

AUDIT_LOG_RETENTION_DAYS = int(_get_int_env("AUDIT_LOG_RETENTION_DAYS", 30))
if AUDIT_LOG_RETENTION_DAYS < 1:
    AUDIT_LOG_RETENTION_DAYS = 1
if AUDIT_LOG_RETENTION_DAYS > 3650:
    AUDIT_LOG_RETENTION_DAYS = 3650

AUDIT_LOG_CLEANUP_INTERVAL_SECONDS = int(_get_int_env("AUDIT_LOG_CLEANUP_INTERVAL_SECONDS", 3600))
if AUDIT_LOG_CLEANUP_INTERVAL_SECONDS < 60:
    AUDIT_LOG_CLEANUP_INTERVAL_SECONDS = 60

AUDIT_LOG_CLEANUP_BATCH_SIZE = int(_get_int_env("AUDIT_LOG_CLEANUP_BATCH_SIZE", 2000))
if AUDIT_LOG_CLEANUP_BATCH_SIZE < 100:
    AUDIT_LOG_CLEANUP_BATCH_SIZE = 100
if AUDIT_LOG_CLEANUP_BATCH_SIZE > 20000:
    AUDIT_LOG_CLEANUP_BATCH_SIZE = 20000
